/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_simulacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Batman
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c2 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        probabilidad = new javax.swing.JTextField();
        txtn = new javax.swing.JTextField();
        txtk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnGO = new javax.swing.JButton();
        kl1 = new javax.swing.JLabel();
        Costo1 = new javax.swing.JLabel();
        kl2 = new javax.swing.JLabel();
        Costo2 = new javax.swing.JLabel();
        kl3 = new javax.swing.JLabel();
        Costo3 = new javax.swing.JLabel();
        CostoT = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Combustible 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 110, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Combustible 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 110, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Combustible 3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 110, 40));
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 90, -1));
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, -1));
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 90, -1));
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 90, -1));
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, -1));
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 90, -1));
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 90, -1));
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 90, -1));
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 90, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pruebas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 70, 30));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("SIMULACIÓN PARA OBTENER LOS LITROS A USAR DE COMBUSTIBLE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -20, 640, 80));
        getContentPane().add(probabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 80, -1));
        getContentPane().add(txtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 80, -1));
        getContentPane().add(txtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 80, -1));

        jLabel7.setText("a");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 41, -1));

        jLabel8.setText("b");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 41, -1));

        jLabel9.setText("c");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 41, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("p");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 48, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("n");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 30, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("k");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 48, -1));

        btnGO.setText("GO");
        btnGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGOActionPerformed(evt);
            }
        });
        getContentPane().add(btnGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 77, -1));

        kl1.setText("kl");
        getContentPane().add(kl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, 20));

        Costo1.setText("Costo");
        getContentPane().add(Costo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        kl2.setText("kl");
        getContentPane().add(kl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 160, 20));

        Costo2.setText("Costo");
        getContentPane().add(Costo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        kl3.setText("kl");
        getContentPane().add(kl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 160, 20));

        Costo3.setText("Costo");
        getContentPane().add(Costo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        CostoT.setText("Costo Total");
        getContentPane().add(CostoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_simulacion/Imagenes/wp2985454.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 440));

        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGOActionPerformed
        double a01 = Double.parseDouble(a1.getText());
        double b01 = Double.parseDouble(b1.getText());
        double c01 = Double.parseDouble(c1.getText());
        double Esperanza =  (a01 + b01 + c01)/3;
        double Var = ((a01*a01)+(b01*b01)+(c01*c01)+(a01*c01)-(a01*b01)-(b01*c01))/18;
        double des = Math.sqrt(Var);
        String varianza = String.valueOf(Var);
        String espe = String.valueOf(Esperanza);
        String desvi = String.valueOf(des);
        //JlaberDes.setText(desvi);
        //jLabel2.setText(varianza);
        //jLabel4.setText(espe);
        double result = 0;
        double pro = 0;
        int cont = 0 ;
         if(a01<b01  & b01<c01){
          double r;
          double comp = ((b01-a01)/(c01-a01));
          for(int i = 0 ; i<100 ; i++){
              r = Math.random()*1;
              cont ++;
               pro += result;
              if(r>=comp){
                  double caso1 = (comp - r)*(c01-a01)*(c01-b01)+((b01-c01)*(b01-c01));
                  if(caso1>0){
                       result = c01 - Math.sqrt(caso1);
                      System.out.println("X" + cont + " " + "es -->" + result);
                 }else{
                      System.out.println("Raiz imaginaria");        
                 }   
                 }else{
                  double caso2 = r*(c01-a01)*(b01-a01);
                  if(caso2>0){
                      result = a01 + Math.sqrt(caso2);
                      System.out.println("X" + cont + " " + "es -->" + result);
                  }else{
                      System.out.println("Raiz imaginaria");
                  }
                  
              }           
          }
         }else{
             JOptionPane.showMessageDialog(null,"la condicion a<b<c no se cumple");
      }
        String x = String.valueOf((pro/100)*1000);
        String c = String.valueOf((pro/100)*1000*125);
           Costo1.setText("Costo $" + c);
         kl1.setText("Kl " + x);
        System.out.println("promedio " + pro/100);
     //-------------------Combustible2--------------------------------
     double a02 = Double.parseDouble(a2.getText());
        double b02 = Double.parseDouble(b2.getText());
        double c02 = Double.parseDouble(c2.getText());
        double Esperanza02 =  (a02 + b02 + c02)/3;
        double Var02 = ((a02*a02)+(b02*b02)+(c02*c02)+(a02*c02)-(a02*b02)-(b02*c02))/18;
        double des02 = Math.sqrt(Var);
        String varianza2 = String.valueOf(Var);
        String espe2 = String.valueOf(Esperanza);
        String desvi2 = String.valueOf(des);
        //JlaberDes.setText(desvi);
        //jLabel2.setText(varianza);
        //jLabel4.setText(espe);
        double result02 = 0;
        double pro02 = 0;
        int cont02 = 0 ;
         if(a02<b02  & b02<c02){
          double r;
          double comp = ((b02-a02)/(c02-a02));
          for(int i = 0 ; i<100 ; i++){
              r = Math.random()*1;
              cont02 ++;
               pro02 += result02;
              if(r>=comp){
                  double caso1 = (comp - r)*(c02-a02)*(c02-b02)+((b02-c02)*(b02-c02));
                  if(caso1>0){
                       result02 = c02 - Math.sqrt(caso1);
                      System.out.println("X" + cont + " " + "es -->" + result02);
                 }else{
                      System.out.println("Raiz imaginaria");        
                 }   
                 }else{
                  double caso2 = r*(c02-a02)*(b02-a02);
                  if(caso2>0){
                      result02 = a02 + Math.sqrt(caso2);
                      System.out.println("X" + cont + " " + "es -->" + result02);
                  }else{
                      System.out.println("Raiz imaginaria");
                  }
                  
              }           
          }
         }else{
             JOptionPane.showMessageDialog(null,"la condicion a<b<c no se cumple");
      }
        String x02 = String.valueOf((pro02/100)*1000);
        String d = String.valueOf((pro02/100)*1000*120);
           Costo2.setText("Costo $" + d);
         kl2.setText("Kl " + x02);
        System.out.println("promedio " + pro02/100);
    //----------------Combustible3-------------------------------------------
    
    double a03 = Double.parseDouble(a3.getText());
        double b03 = Double.parseDouble(b3.getText());
        double c03 = Double.parseDouble(c3.getText());
        double Esperanza03 =  (a03 + b03 + c03)/3;
        double Var03 = ((a03*a03)+(b03*b03)+(c03*c03)+(a03*c03)-(a03*b03)-(b03*c03))/18;
        double des03 = Math.sqrt(Var);
        String varianza3 = String.valueOf(Var03);
        String espe3 = String.valueOf(Esperanza03);
        String desvi3 = String.valueOf(des03);
        //JlaberDes.setText(desvi);
        //jLabel2.setText(varianza);
        //jLabel4.setText(espe);
        double result03 = 0;
        double pro03 = 0;
        int cont03 = 0 ;
         if(a03<b03  & b03<c03){
          double r;
          double comp = ((b03-a03)/(c03-a03));
          for(int i = 0 ; i<100 ; i++){
              r = Math.random()*1;
              cont03 ++;
               pro03 += result02;
              if(r>=comp){
                  double caso1 = (comp - r)*(c03-a03)*(c03-b03)+((b03-c03)*(b03-c03));
                  if(caso1>0){
                       result03 = c03 - Math.sqrt(caso1);
                      System.out.println("X" + cont03 + " " + "es -->" + result03);
                 }else{
                      System.out.println("Raiz imaginaria");        
                 }   
                 }else{
                  double caso2 = r*(c03-a03)*(b03-a03);
                  if(caso2>0){
                      result03 = a03 + Math.sqrt(caso2);
                      System.out.println("X" + cont03 + " " + "es -->" + result03);
                  }else{
                      System.out.println("Raiz imaginaria");
                  }
                  
              }           
          }
         }else{
             JOptionPane.showMessageDialog(null,"la condicion a<b<c no se cumple");
      }
        String x03 = String.valueOf((pro03/100)*1000);
        String e = String.valueOf((pro03/100)*1000*200);
           Costo3.setText("Costo $" + e);
         kl3.setText("Kl " + x03);
        System.out.println("promedio " + pro03/100);
    //-----------------------Binomial---------------------------------------------
    Binomial bi = new Binomial ();
    
    double p = Double.parseDouble(probabilidad.getText());
    int n = Integer.parseInt(txtn.getText());
    double k = Double.parseDouble(txtk.getText());
    int contador = 0;
    double costo1 = (pro/100)*1000*125;
    double costo2 = (pro02/100)*1000*120;
    double costo3 = (pro03/100)*1000*200;
    double costoT = 0;
    double prom = 0;
    
        //for (int i = 0; i < 10; i++) {
            
                if(p == 0.9){
                    int f = bi.Bin(p,n);
                    if (f<=k){
                    costoT = costo1*k;
                    }else{
                    costoT = costo1*k + costo1*(f-k);
                    }
            }   
                if(p == 0.7){
                   int f2 = bi.Bin(p,n);
                    if(f2<k){
                        costoT = costo2*k;
                    }else{
                        costoT = costo2*k + costo2*(f2-k);
                    }
                }
                if(p==0.8){
                    int f3 = bi.Bin(p,n);
                     if(f3<k){
                         costoT = costo3*k;
                     }else{
                         costoT = costo3*k + costo3*(f3-k);
                     }   
                }
                
               String cos = String.valueOf(costoT);
               CostoT.setText("Costo total $" + cos);
                    
          //}
        
    }//GEN-LAST:event_btnGOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Costo1;
    private javax.swing.JLabel Costo2;
    private javax.swing.JLabel Costo3;
    private javax.swing.JLabel CostoT;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JButton btnGO;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel kl1;
    private javax.swing.JLabel kl2;
    private javax.swing.JLabel kl3;
    private javax.swing.JTextField probabilidad;
    private javax.swing.JTextField txtk;
    private javax.swing.JTextField txtn;
    // End of variables declaration//GEN-END:variables
}
